# Database Configuration
db.url=jdbc:mysql://localhost:3306/biosync
db.username=root
# MySQL Driver
db.driver=com.mysql.cj.jdbc.Driver

# MAILJET Configuration
mailjet.api.key=14d04af078c204dbda952989bfb8ad69
mailjet.api.secret=4b9dfda51168092eedbafccff1c360dd
mailjet.from.email=mohamedmehdi.hajouni@esprit.tn
mailjet.from.name=BioSync
